# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: General Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./src
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./src

    - name: Publish
      working-directory: ./src
      run: |
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release . -o ./out

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4

      with:
        name: webapp
        path: ./src/out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: webapp

    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'loadStorm'
        package: .

  loadtest:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Azure Load Testing'
      uses: azure/load-testing@v1
      with:
        loadTestConfigFile: ./TestFiles/basic-tests.yaml
        loadTestResource: 'loadStorm'
        resourceGroup: 'loadStorm' 
        # env: |
        #   [
        #       {
        #       "name": "<Name of the variable>",
        #       "value": "<Value of the variable>"
        #       },
        #       {
        #       "name": "<Name of the variable>",
        #       "value": "<Value of the variable>"
        #       }
        #   ]  